### ISSUE TITLE
Вынести настройки из ресурсов

### ISSUE THREAD

**Issue by zhum** [Izaron/OctoshellBot#2]
Крайне неудобно при смене настроек перекомпилировать весть проект. Предлагаю вынести файл application.yml (или его часть) из проекта и считывать настройки динамически при старте.

**Comment by Izaron** [comment]
Да, действительно. К счастью, есть возможность так сделать.
Когда мы запускаем проект, то делаем это через команду `java -jar octoshell-bot-0.0.1-SNAPSHOT.jar`.

Чтобы выбрать какой-то другой файл настроек, нужно при вызове устанавливать spring.config.location, делается это так:
`java -jar octoshell-bot-0.0.1-SNAPSHOT.jar --spring.config.location=PATH_TO_FILE`,
где `PATH_TO_FILE` - путь до конфигурационного файла, может быть как абсолютный путь, так и относительный путь.

Например, я у себя могу сделать так:
`java -jar octoshell-bot-0.0.1-SNAPSHOT.jar --spring.config.location=/home/izaron/octoshell-bot/src/main/resources/application.yml`.

Но изменять файл настроек во время работы программы оно не даёт - нужно остановить программу, и запустить ее снова с указанием пути. Хотя перекомпилировать уже не нужно.
